import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import { createWorkspaceBackup, createDefaultWorkspace, WORKSPACE_KEY } from '../../src/workspaceData.js';
import {useBrowser,token} from './harness.mjs';
const open=useBrowser();
for(const v of [9,10])test(`saved v${v} workspace upgrades without losing custom data or old key`,async()=>{
 const raw=readFileSync(new URL(`../fixtures/workspace-v${v}.json`,import.meta.url),'utf8');
 const key=`football-os.playbooks.v${v}`;
 const app=await open({storage:{[key]:raw}}),{page}=app;
 assert.match(await page.locator('.title-line h1').innerText(),new RegExp(`Saved custom v${v}`));
 const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),WORKSPACE_KEY);
 assert.equal(saved.version,11);assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),raw);
 const before=JSON.parse(raw).playbooks[0].plays[0],after=saved.playbooks[0].plays[0];
 assert.deepEqual(after.players,before.players);assert.deepEqual(after.assignments.map(a=>a.points),before.assignments.map(a=>a.points));
 app.assertNoErrors();await app.close();
});
test('corrupt current data stays intact through reload and recovers only after confirmed restore',async()=>{
 const raw='{broken original';const app=await open({storage:{[WORKSPACE_KEY]:raw}}),{page}=app;
 assert.match(await page.locator('.storage-recovery').innerText(),/Read-only recovery/);
 assert.equal(await page.getByRole('button',{name:'More',exact:true}).isDisabled(),true);
 await token(page,'X').click();await page.keyboard.press('ArrowRight');
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),WORKSPACE_KEY),raw);
 await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(700);
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),WORKSPACE_KEY),raw);
 await page.getByRole('button',{name:'Open backup and recovery'}).click();
 assert.equal(await page.getByRole('button',{name:/Download backup/}).isDisabled(),true);
 const backup=createWorkspaceBackup(createDefaultWorkspace());
 await page.locator('input[type=file]').setInputFiles({name:'recovery.footballos',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 await page.getByRole('button',{name:'Restore this backup'}).click();await page.waitForTimeout(700);
 assert.equal(await page.locator('.storage-recovery').count(),0);
 const recovered=await page.evaluate(()=>JSON.parse(localStorage.getItem('football-os.recovery.v1')));
 assert.equal(recovered.raw,raw);
 assert.equal(await page.getByRole('button',{name:'More',exact:true}).isDisabled(),false);
 app.assertNoErrors();await app.close();
});
test('quota failure is persistent and a failed recovery copy cannot replace the workspace',async()=>{
 const app=await open(),{page}=app;
 const original=await page.evaluate(k=>localStorage.getItem(k),WORKSPACE_KEY);
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});
 await token(page,'X').click();await page.keyboard.press('ArrowRight');await page.waitForTimeout(700);
 assert.match(await page.locator('.storage-recovery').innerText(),/Changes could not be saved/);
 await page.getByRole('button',{name:'Open backup and recovery'}).click();
 const candidate=createWorkspaceBackup(createDefaultWorkspace());candidate.workspace.playbooks[0].plays[0].name='Replacement';
 await page.locator('input[type=file]').setInputFiles({name:'replacement.footballos',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(candidate))});
 await page.getByRole('button',{name:'Restore this backup'}).click();
 assert.match(await page.locator('.restore-error').innerText(),/not restored/);
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),WORKSPACE_KEY),original);
 assert.notEqual(await page.locator('.title-line h1').innerText(),'Replacement');
 app.assertNoErrors();await app.close();
});
test('corrupt game-day data is retained and does not get deleted by the null-state effect',async()=>{
 const key='football-os.game-day.v7',raw='{bad snapshot';
 const app=await open({storage:{[key]:raw}}),{page}=app;
 assert.match(await page.locator('.storage-recovery').innerText(),/game-day adjustment/);
 assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),raw);
 await page.getByRole('button',{name:'More',exact:true}).click();
 assert.equal(await page.getByRole('menuitem',{name:'Game Day Adjust'}).isDisabled(),true);
 app.assertNoErrors();await app.close();
});
